import pandas as pd
df = pd.read_csv('mc_recovery_results.csv')
print('Classical F:')
print(f'  Mean = {df["f_stat_classical"].mean():,.0f}')
print(f'  Min  = {df["f_stat_classical"].min():,.0f} (rep #{df["f_stat_classical"].idxmin()+1})')
print(f'  Max  = {df["f_stat_classical"].max():,.0f} (rep #{df["f_stat_classical"].idxmax()+1})')
print()
print('Cluster-robust F:')
print(f'  Mean = {df["f_stat_cluster"].mean():,.0f}')
print(f'  Min  = {df["f_stat_cluster"].min():,.0f} (rep #{df["f_stat_cluster"].idxmin()+1})')
print(f'  Max  = {df["f_stat_cluster"].max():,.0f} (rep #{df["f_stat_cluster"].idxmax()+1})')
print()
print(f'Average absolute difference: {(df["f_stat_classical"] - df["f_stat_cluster"]).abs().mean():,.0f}')
print(f'Correlation: {df["f_stat_classical"].corr(df["f_stat_cluster"]):.4f}')
